---
version: 2.0
jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - run:
          name: Hello world!
          command: echo "Hello world!"
    working_directory: /usr/src/protoc_docs_plugin/

  unit-python2.7:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: Install pandoc
          command: apt-get update && apt-get install -y pandoc
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-2.7
    working_directory: /usr/src/protoc_docs_plugin/

  unit-python3.5:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run:
          name: Install pandoc
          command: apt-get update && apt-get install -y pandoc
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.5
    working_directory: /usr/src/protoc_docs_plugin/

  unit-python3.6:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: Install pandoc
          command: apt-get update && apt-get install -y pandoc
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.6
    working_directory: /usr/src/protoc_docs_plugin/

  unit-python3.7:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install pandoc
          command: apt-get update && apt-get install -y pandoc
      - run:
          name: Install nox and codecov.
          command: pip install --upgrade nox codecov
      - run:
          name: Run unit tests.
          command: nox -s unit-3.7
    working_directory: /usr/src/protoc_docs_plugin/

workflows:
  version: 2
  tests:
    jobs:
      - unit-python2.7
      - unit-python3.5
      - unit-python3.6
      - unit-python3.7
